name: sdf_dro
channels:
  - nvidia/label/cuda-11.8.0
  - conda-forge
dependencies:
  - python=3.10                   # Fix version for reproducibility  # |
  - numpy <2.0.0
  - wandb
  - pip
  - cuda-toolkit
  - ipython
  - matplotlib
  - tqdm
  - pandas
  - pip:
    - napf
    - open3d
    - pyvista
    - pymcubes
    - trimesh
